import escopeta from "../../assets/icons/escopeta.png"
import armadura from "../../assets/icons/armadura.png"
import shield from "../../assets/icons/shield.png"
import ship from "../../assets/mapa/space-ship.webp"
import type { Weapon } from "../models/items-fight.interfaces"

export const ARMORY: Record<number, Weapon> ={
    999: {
      nombre: 'Puños',
      descripcion: '',
      id: 999,
      type: 'weapon',
      icon: null,
      damage: 1,
      defense: 0,
      uses: 0,
    },
    0: {
      nombre: 'Escopeta',
      descripcion: 'Arma antigua',
      id: 0,
      type: 'weapon',
      icon: escopeta,
      damage: 5,
      defense: 0,
      uses: 0,
    },
    1: {
      nombre: 'Armadura',
      descripcion: 'Armadura antigua',
      id: 1,
      type: 'armor',
      icon: armadura,
      damage: 0,
      defense: 3,
      uses: 0,
    },
    2: {
      nombre: 'Escudo',
      descripcion: 'Escudo',
      id: 2,
      type: 'shield',
      icon: shield,
      damage: 0,
      defense: 1,
      uses: 0,
    },
    3: {
      nombre: 'Escopeta 2',
      descripcion: 'Arma antigua',
      id: 3,
      type: 'weapon',
      icon: '',
      damage: 0,
      defense: 0,
      uses: 0,
    },
    // Habitaciones nave espacialCIVIL (5)
    100001:{
    nombre: 'Sala de Comando',
    descripcion: 'Centro de control principal de la nave',
    id: 100001,
    type: 'room_civil',
    icon: ship,
    damage: 0,
    defense: 0,
    uses: 5,
  },
  100002:{
    nombre: 'Cuartos de Tripulación',
    descripcion: 'Área de descanso para la tripulación',
    id: 100002,
    type: 'room_civil',
    icon: ship,
    damage: 0,
    defense: 0,
    uses: 3,
  },
  100003:{
    nombre: 'Laboratorio Científico',
    descripcion: 'Investigación y análisis de muestras',
    id: 100003,
    type: 'room_civil',
    icon: ship,
    damage: 0,
    defense: 0,
    uses: 4,
  },
  100004:{
    nombre: 'Comedor Espacial',
    descripcion: 'Zona de alimentación',
    id: 100004,
    type: 'room_civil',
    icon: ship,
    damage: 0,
    defense: 0,
    uses: 6,
  },
  100005:{
    nombre: 'Centro Médico',
    descripcion: 'Atención sanitaria de emergencia',
    id: 100005,
    type: 'room_civil',
    icon: ship,
    damage: 0,
    defense: 0,
    uses: 5,
  },

  // ARMAS (5)
  100006:{
    nombre: 'Cañón Láser Frontal',
    descripcion: 'Arma principal de ataque directo',
    id: 100006,
    type: 'room_weapon',
    icon: ship,
    damage: 15,
    defense: 0,
    uses: 10,
  },
  100007:{
    nombre: 'Lanzamisiles Orbital',
    descripcion: 'Sistema de misiles guiados',
    id: 100007,
    type: 'room_weapon',
    icon: ship,
    damage: 20,
    defense: 0,
    uses: 5,
  },
  100008:{
    nombre: 'Torreta Automática',
    descripcion: 'Defensa activa de disparo rápido',
    id: 100008,
    type: 'room_weapon',
    icon: ship,
    damage: 10,
    defense: 0,
    uses: 12,
  },
  100009:{
    nombre: 'Rayo de Plasma',
    descripcion: 'Descarga energética concentrada',
    id: 100009,
    type: 'room_weapon',
    icon: ship,
    damage: 18,
    defense: 0,
    uses: 8,
  },
  100010:{
    nombre: 'Campo de Minas Espaciales',
    descripcion: 'Dispositivo de defensa ofensiva',
    id: 100010,
    type: 'room_weapon',
    icon: ship,
    damage: 25,
    defense: 0,
    uses: 3,
  },

  // ESCUDOS (5)
  100011:{
    nombre: 'Escudo Deflector Primario',
    descripcion: 'Protección básica contra impactos',
    id: 100011,
    type: 'room_shield',
    icon: ship,
    damage: 0,
    defense: 15,
    uses: 10,
  },
  100012:{
    nombre: 'Campo Energético Reforzado',
    descripcion: 'Escudo de alta resistencia',
    id: 100012,
    type: 'room_shield',
    icon: ship,
    damage: 0,
    defense: 20,
    uses: 8,
  },
  100013:{
    nombre: 'Barrera Antimateria',
    descripcion: 'Protección contra armas avanzadas',
    id: 100013,
    type: 'room_shield',
    icon: ship,
    damage: 0,
    defense: 25,
    uses: 5,
  },
  100014:{
    nombre: 'Escudo Reflector',
    descripcion: 'Desvía ataques energéticos',
    id: 100014,
    type: 'room_shield',
    icon: ship,
    damage: 0,
    defense: 18,
    uses: 7,
  },
  100015:{
    nombre: 'Blindaje Cuántico',
    descripcion: 'Tecnología experimental defensiva',
    id: 100015,
    type: 'room_shield',
    icon: ship,
    damage: 0,
    defense: 30,
    uses: 4,
  }
}