import escopeta from "../../assets/icons/escopeta.png"
import escopetaFuego from "../../assets/icons/escopeta-fuego.png"

import armadura from "../../assets/icons/armadura.png"
import dagas from "../../assets/icons/dagas.png"

import shield from "../../assets/icons/shield.png"
import shieldEnergy from "../../assets/icons/shield-energy.png"
import shieldFire from "../../assets/icons/shield-fire.png"
import shieldSpikes from "../../assets/icons/shield-spykes.png"

import armor1 from "../../assets/icons/room_armor/armor1.png";
import armor2 from "../../assets/icons/room_armor/armor2.png";
import armor3 from "../../assets/icons/room_armor/armor3.png";
import armor4 from "../../assets/icons/room_armor/armor4.png";
import armor5 from "../../assets/icons/room_armor/armor5.png";

import weapon1 from "../../assets/icons/room_weapon/weapon1.png"
import weapon2 from "../../assets/icons/room_weapon/weapon2.png"
import weapon3 from "../../assets/icons/room_weapon/weapon3.png"
import weapon4 from "../../assets/icons/room_weapon/weapon4.png"
import weapon5 from "../../assets/icons/room_weapon/weapon5.png"

import speed1 from "../../assets/icons/room_speed/speed1.png"
import speed2 from "../../assets/icons/room_speed/speed2.png"
import speed3 from "../../assets/icons/room_speed/speed3.png"
import speed4 from "../../assets/icons/room_speed/speed4.png"
import speed5 from "../../assets/icons/room_speed/speed5.png"

import type { Weapon } from "../models/items-fight.interfaces"

export const ARMORY: Record<number, Weapon> ={
    999: {
      nombre: 'Puños',
      descripcion: '',
      id: 999,
      type: 'weapon',
      icon: null,
      damage: 1,
      defense: 0,
      uses: 0,
      metales: 12,
      nucleosEnergeticos: 5,
      circuito: 3,
      cristales: 4,
    },
    1000: {
      nombre: 'Sin Armadura',
      descripcion: '',
      id: 999,
      type: 'armor',
      icon: null,
      damage: 0,
      defense: 0,
      uses: 0,
      metales: 12,
      nucleosEnergeticos: 5,
      circuito: 3,
      cristales: 4,
    },
    1001: {
      nombre: 'Sin Escudo',
      descripcion: '',
      id: 999,
      type: 'shield',
      icon: null,
      damage: 0,
      defense: 0,
      uses: 0,
      metales: 12,
      nucleosEnergeticos: 5,
      circuito: 3,
      cristales: 4,
    },
    0: {
      nombre: 'Escopeta',
      descripcion: 'Arma antigua',
      id: 0,
      type: 'weapon',
      icon: escopeta,
      damage: 5,
      defense: 0,
      uses: 0,
      metales: 12,
      nucleosEnergeticos: 5,
      circuito: 3,
      cristales: 4,
    },
    1: {
      nombre: 'Dagas Dobles',
      descripcion: 'Son dos dagas',
      id: 1,
      type: 'weapon',
      icon: dagas,
      damage: 1,
      defense: 0,
      uses: 3,
      actions: 2,
      metales: 12,
      nucleosEnergeticos: 0,
      circuito: 0,
      cristales: 2,
    },
    2: {
      nombre: 'Armadura',
      descripcion: 'Armadura antigua',
      id: 2,
      type: 'armor',
      icon: armadura,
      damage: 0,
      defense: 3,
      uses: 0,
      metales: 12,
      nucleosEnergeticos: 5,
      circuito: 3,
      cristales: 4,
    },
    3: {
      nombre: 'Escudo',
      descripcion: 'Escudo',
      id: 3,
      type: 'shield',
      icon: shield,
      damage: 0,
      defense: 1,
      uses: 0,
      metales: 12,
      nucleosEnergeticos: 5,
      circuito: 3,
      cristales: 4,
    },
    4: {
      nombre: 'Escopeta de fuego',
      descripcion: 'Arroja fuego, 10% de prender fuego',
      id: 4,
      type: 'weapon',
      icon: escopetaFuego,
      damage: 0,
      defense: 0,
      uses: 0,
      metales: 12,
      nucleosEnergeticos: 5,
      circuito: 3,
      cristales: 4,
      special: 'slowness',
      prop: 1
    },
    5: {
      nombre: 'Escudo de Energia',
      descripcion: 'Escudo',
      id: 5,
      type: 'shield',
      icon: shieldEnergy,
      damage: 0,
      defense: 1,
      uses: 0,
      metales: 12,
      nucleosEnergeticos: 5,
      circuito: 3,
      cristales: 4,
    },
    6: {
      nombre: 'Escudo de Fuego',
      descripcion: 'Escudo',
      id: 6,
      type: 'shield',
      icon: shieldFire,
      damage: 0,
      defense: 1,
      uses: 0,
      metales: 12,
      nucleosEnergeticos: 5,
      circuito: 3,
      cristales: 4,
    },
    7: {
      nombre: 'Escudo de Puas',
      descripcion: 'Escudo',
      id: 7,
      type: 'shield',
      icon: shieldSpikes,
      damage: 0,
      defense: 1,
      uses: 0,
      metales: 12,
      nucleosEnergeticos: 5,
      circuito: 3,
      cristales: 4,
    },
    // Habitaciones nave espacialCIVIL (5)
    100001:{
    nombre: 'Sala de Comando',
    descripcion: 'Centro de control principal de la nave',
    id: 100001,
    type: 'room_civil',
    icon: speed1,
    damage: 0,
    defense: 0,
    uses: 5,
    metales: 12,
    nucleosEnergeticos: 5,
    circuito: 3,
    cristales: 4,
  },
  100002:{
    nombre: 'Cuartos de Tripulación',
    descripcion: 'Área de descanso para la tripulación',
    id: 100002,
    type: 'room_civil',
    icon: speed2,
    damage: 0,
    defense: 0,
    uses: 3,
    metales: 12,
    nucleosEnergeticos: 5,
    circuito: 3,
    cristales: 4,
  },
  100003:{
    nombre: 'Laboratorio Científico',
    descripcion: 'Investigación y análisis de muestras',
    id: 100003,
    type: 'room_civil',
    icon: speed3,
    damage: 0,
    defense: 0,
    uses: 4,
    metales: 12,
    nucleosEnergeticos: 5,
    circuito: 3,
    cristales: 4,
  },
  100004:{
    nombre: 'Comedor Espacial',
    descripcion: 'Zona de alimentación',
    id: 100004,
    type: 'room_civil',
    icon: speed4,
    damage: 0,
    defense: 0,
    uses: 6,
    metales: 12,
    nucleosEnergeticos: 5,
    circuito: 3,
    cristales: 4,
  },
  100005:{
    nombre: 'Centro Médico',
    descripcion: 'Atención sanitaria de emergencia',
    id: 100005,
    type: 'room_civil',
    icon: speed5,
    damage: 0,
    defense: 0,
    uses: 5,
    metales: 12,
    nucleosEnergeticos: 5,
    circuito: 3,
    cristales: 4,
  },

  // ARMAS (5)
  100006:{
    nombre: 'Cañón Láser Frontal',
    descripcion: 'Arma principal de ataque directo',
    id: 100006,
    type: 'room_weapon',
    icon: weapon1,
    damage: 15,
    defense: 0,
    uses: 10,
    metales: 12,
    nucleosEnergeticos: 5,
    circuito: 3,
    cristales: 4,
  },
  100007:{
    nombre: 'Lanzamisiles Orbital',
    descripcion: 'Sistema de misiles guiados',
    id: 100007,
    type: 'room_weapon',
    icon: weapon2,
    damage: 20,
    defense: 0,
    uses: 5,
    metales: 12,
    nucleosEnergeticos: 5,
    circuito: 3,
    cristales: 4,
  },
  100008:{
    nombre: 'Torreta Automática',
    descripcion: 'Defensa activa de disparo rápido',
    id: 100008,
    type: 'room_weapon',
    icon: weapon3,
    damage: 10,
    defense: 0,
    uses: 12,
    metales: 12,
    nucleosEnergeticos: 5,
    circuito: 3,
    cristales: 4,
  },
  100009:{
    nombre: 'Rayo de Plasma',
    descripcion: 'Descarga energética concentrada',
    id: 100009,
    type: 'room_weapon',
    icon: weapon4,
    damage: 18,
    defense: 0,
    uses: 8,
    metales: 12,
      nucleosEnergeticos: 5,
      circuito: 3,
      cristales: 4,
  },
  100010:{
    nombre: 'Campo de Minas Espaciales',
    descripcion: 'Dispositivo de defensa ofensiva',
    id: 100010,
    type: 'room_weapon',
    icon: weapon5,
    damage: 25,
    defense: 0,
    uses: 3,
    metales: 12,
      nucleosEnergeticos: 5,
      circuito: 3,
      cristales: 4,
  },

  // ESCUDOS (5)
  100011:{
    nombre: 'Escudo Deflector Primario',
    descripcion: 'Protección básica contra impactos',
    id: 100011,
    type: 'room_shield',
    icon: armor1,
    damage: 0,
    defense: 15,
    uses: 10,
    metales: 12,
      nucleosEnergeticos: 5,
      circuito: 3,
      cristales: 4,
  },
  100012:{
    nombre: 'Campo Energético Reforzado',
    descripcion: 'Escudo de alta resistencia',
    id: 100012,
    type: 'room_shield',
    icon: armor2,
    damage: 0,
    defense: 20,
    uses: 8,
    metales: 12,
      nucleosEnergeticos: 5,
      circuito: 3,
      cristales: 4,
  },
  100013:{
    nombre: 'Barrera Antimateria',
    descripcion: 'Protección contra armas avanzadas',
    id: 100013,
    type: 'room_shield',
    icon: armor3,
    damage: 0,
    defense: 25,
    uses: 5,
    metales: 12,
    nucleosEnergeticos: 5,
    circuito: 3,
    cristales: 4,
  },
  100014:{
    nombre: 'Escudo Reflector',
    descripcion: 'Desvía ataques energéticos',
    id: 100014,
    type: 'room_shield',
    icon: armor4,
    damage: 0,
    defense: 18,
    uses: 7,
    metales: 12,
    nucleosEnergeticos: 5,
    circuito: 3,
    cristales: 4,
  },
  100015:{
    nombre: 'Blindaje Cuántico',
    descripcion: 'Tecnología experimental defensiva',
    id: 100015,
    type: 'room_shield',
    icon: armor5,
    damage: 0,
    defense: 30,
    uses: 4,
    metales: 12,
    nucleosEnergeticos: 5,
    circuito: 3,
    cristales: 4,
  }
}